### ISSUE TITLE
Update the documentation for backups

### ISSUE THREAD

**Issue by mygrexit** [truecharts/truetool#147]
### Is your feature request related to a problem?

Thanks to Truecharts it has become very easy to install apps. Unfortunately, the backup aspect doesn't get enough attention in my opinion. 

There is this sections of course:
https://truecharts.org/docs/manual/SCALE%20Apps/backup-restore/

But it's just a little confusing, because at the beginning it references the new Truetool first (however, that might've been my blindness).

Moreover, the backup process refers exclusively to an Replications Task. I assume that many people only do cloud backups and the instructions do not apply there.

### Describe the solution you'd like

As I said at the beginning, I think the backup process should be top priority.

Simplification of such topics (e.g. app installation / Virtualization etc.) always attracts people who do not have an IT background. You could argue that people are responsible for the backups themselves, but even I as an IT-savvy person have no idea how to create reasonable cloud backups of the apps.

Therefore I would love an updated and expanded documentation.

### Describe alternatives you've considered

None :-)

### Additional context

I appreciate your work and your dedication. Thanks!

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
Not related to TrueTool
TrueTool is just a tool to trigger the SCALE API, it has nothing to do with off-site backups.

Simply put:
The documentation is a seperate project, but we also don't accept issues for documentation. Otherwise we would have 999999 open issues with "this page can be made beter".
We know, either do it yourself or wait until someone has the time, basically.

Anyway, on-topic:
Off-site backups (which is **NOT** the same as Apps backups done with TrueTool, see the docs you linked), can **ONLY** be done using `zfs send-recv` there is no option to use cloud-backups, nor do we support it.

In theory(!) one can do `zfs send` into go a `.tgz` archive, but we're not going out-of-our way to support it.

As stated in our guides (the important first guide you might have missed), this guide and TrueTool are a stop-gap measure. If you want things like a better backup solution, please contact iX Systems to put pressure on them. Because it's actually their responsibility.
